# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      PACKAGE_PASSWORD: ${{ secrets.PACKAGE_PASSWORD }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install numpy tqdm

      - name: Configure reticulate Python
        run: |
          python -c "import numpy; import tqdm"

      - name: Install 7-Zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Extract encrypted archive
        run: |

          ZIPFILE=$(find . -type f -name "*.tar.gz.zip" -print -quit)
          
          mkdir -p extracted
          7z x -p"$PACKAGE_PASSWORD" "$ZIPFILE" -oextracted
          
          TARFILE=$(find extracted -type f -name "*.tar.gz" -print -quit)
          echo "TARFILE=$TARFILE" >> "$GITHUB_ENV"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: .
          extra-packages: any::pkgdown, any::reticulate, any::Rcpp, any::RcppEigen, any::tinytest, any::pkgdown, any::remotes
          needs: website

      - name: Extract package source
        run: |
          tar -xzf "$TARFILE"

      - name: Detect package directory
        run: |
          PKGDIR=$(tar -tzf "$TARFILE" | head -n 1 | cut -d/ -f1)
          echo "PKGDIR=$PKGDIR" >> "$GITHUB_ENV"

      - name: Debug package input
        shell: bash
        run: |
          echo "PKGDIR=$PKGDIR"
          echo "TARFILE=$TARFILE"
          ls -la "$PKGDIR"

      # - name: Install package dependencies
      #   run: |
      #     Rscript -e 'install.packages(c("reticulate", "Rcpp", "RcppEigen", "tinytest", "remotes", "pkgdown"))'


      - name: Install package dependencies
        run: |
          Rscript -e 'remotes::install_deps(Sys.getenv("PKGDIR"), dependencies = TRUE, upgrade = "never")'

      - name: Install package
        run: |
          R CMD INSTALL "$TARFILE"

      - name: Build pkgdown site
        run: |
          Rscript -e 'pkgdown::build_site(pkg = Sys.getenv("PKGDIR"))'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PKGDIR }}/docs

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
